title: Jun Taek Lee
description: My Personal Website
author: Jun Taek Lee
logo: "https://raw.githubusercontent.com/leejunta/webpage/gh-pages/assets/Images/profile.jpg"
github: https://github.com/leejunta
about: Data Scientist (leejunta@grinnell.edu)

baseurl: "https://leejunta.github.io/webpage/"
url: "https://leejunta.github.io/webpage/"

disqus_shortname: aboutjt
google_analytics: UA-93050072-1

share:
  twitter_username: \#
  fb_appid: 1360178324043921

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
